"""Prepare the local data plane for the Konnect control plane.

  KONNECT_PAT_FILE=~/.kong/kpat uv run python -m guardrail_studio.bootstrap

1. Finds the control plane (default: guardrail-service).
2. Creates a self-signed DP client certificate in kong/certs/ if missing.
3. Pins it on the control plane (pki_client_certs auth).
4. Writes kong/konnect.env with the cluster and telemetry endpoints (no secrets).
"""

from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys

from guardrail_studio.deploy import locate
from guardrail_studio.konnect import Konnect, load_token

ROOT = pathlib.Path(__file__).resolve().parents[2]


def ensure_cert(certs: pathlib.Path, cn: str) -> tuple[pathlib.Path, pathlib.Path]:
    certs.mkdir(parents=True, exist_ok=True)
    crt, key = certs / "tls.crt", certs / "tls.key"
    if not crt.exists():
        subprocess.run(
            ["openssl", "req", "-new", "-x509", "-nodes", "-newkey", "ec", "-pkeyopt", "ec_paramgen_curve:secp384r1",
             "-keyout", str(key), "-out", str(crt), "-days", "1095", "-subj", f"/CN={cn}"],
            check=True, capture_output=True,
        )
        key.chmod(0o600)
        print(f"generated {crt.relative_to(ROOT)}")
    return crt, key


def host_of(url: str) -> str:
    return url.removeprefix("https://").rstrip("/")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--control-plane", default="guardrail-service")
    ap.add_argument("--region")
    args = ap.parse_args(argv)

    token = load_token()
    region, cp = locate(token, args.control_plane, args.region)
    if cp is None:
        print(f"control plane '{args.control_plane}' not found; run guardrail_studio.deploy --create first")
        return 2
    crt, _ = ensure_cert(ROOT / "kong" / "certs", f"{args.control_plane}-dp")
    with Konnect(token, region) as k:
        added = k.ensure_dp_certificate(cp["id"], crt.read_text())
    print(("pinned" if added else "already pinned") + f" DP certificate on {cp['name']}")

    cp_host = host_of(cp["config"]["control_plane_endpoint"])
    tp_host = host_of(cp["config"]["telemetry_endpoint"])
    env = ROOT / "kong" / "konnect.env"
    env.write_text(
        "# Generated by guardrail_studio.bootstrap. Endpoints only, no secrets.\n"
        f"KONG_CLUSTER_CONTROL_PLANE={cp_host}:443\n"
        f"KONG_CLUSTER_SERVER_NAME={cp_host}\n"
        f"KONG_CLUSTER_TELEMETRY_ENDPOINT={tp_host}:443\n"
        f"KONG_CLUSTER_TELEMETRY_SERVER_NAME={tp_host}\n"
    )
    print(f"wrote {env.relative_to(ROOT)} (control plane {cp_host})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
